site_name: 学习笔记

theme: material
pages:
    - index.md
    - '金融数学':
        - '概率论':
            - '概率分布': 'FinMath/dist.md'
            - '更新过程': 'FinMath/renewal.md'
            - '排队论': 'FinMath/queue.md'
        - '衍生品数学':
            - '随机积分': FinMath/stocal.md
            - '期权定价': FinMath/option.md
            - '随机波动率': FinMath/stoval.md
        - '优化':
            - '线性优化': FinMath/linopt.md
            - '凸优化': FinMath/cvxopt.md
            - '随机控制': FinMath/stocon.md
    - '交易策略':
        - '订单簿': Algo/LOB.md
        - '做市': Algo/MM.md
        - '因子模型': Algo/FactorModel.md
        - '统计套利': Algo/StatArb.md
        - '算法交易': Algo/Algo.md
    - '编程语言':
        - '设计模式': 'ProgLag/designpatterns.md'
        - 'C++':
            - 'C++': 'ProgLag/CPP/CPP.md'
        - 'Python':
            - 'Python': 'ProgLag/Python.md'
        - 'C#': 
            - 'C#': 'ProgLag/C#.md'
    - '系统编程':
        - 'IO系统编程': 'System/IO.md'
        - '进程': 'System/Process.md'


    - '关于': about.md

extra:
  social:
    - type: 'github'
      link: 'https://github.com/stanleywu111'
  disqus: 'mywiki-1'
    
extra_javascript: 
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - pymdownx.tasklist:
        custom_checkbox: true
    - mdx_math:
        enable_dollar_delimiter: True
    - codehilite